"""
LLM Recommendations Service 
===========================
Uses a local Ollama instance (primary) or Google Gemini API (fallback) 
to generate actionable agronomic recommendations for the farmer based 
on the diagnostic and yield prediction outputs from Models A, B, C, and D.

Priority: Ollama (local, free) → Gemini (cloud, API key required)
"""

import os
import json
import requests
import textwrap

# ── Ollama Config (Primary — Local) ──
OLLAMA_URL = "http://localhost:11434/api/generate"
DEFAULT_OLLAMA_MODEL = "llama3.2"

# ── Gemini Config (Fallback — Cloud) ──
GEMINI_MODEL = "gemini-2.5-flash"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

def _try_ollama(prompt, model_name):
    """Attempt to get a response from local Ollama. Returns dict or None."""
    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False,
        "temperature": 0.4
    }
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=120)
        response.raise_for_status()
        result = response.json()
        text = result.get("response", "")
        if text:
            print(f"[LLM] [OK] Ollama ({model_name}) responded successfully.")
            return {
                "status": "success",
                "model_used": f"{model_name} (Ollama - Local)",
                "recommendation": text
            }
    except requests.exceptions.ConnectionError:
        print("[LLM] [ERROR] Ollama not reachable — will try Gemini fallback.")
    except requests.exceptions.Timeout:
        print("[LLM] [ERROR] Ollama timed out — will try Gemini fallback.")
    except requests.exceptions.RequestException as e:
        print(f"[LLM] [ERROR] Ollama error: {e} — will try Gemini fallback.")
    return None

def _try_gemini(prompt):
    """Attempt to get a response from Google Gemini API. Returns dict or None."""
    if not GEMINI_API_KEY:
        print("[LLM] [ERROR] Gemini fallback skipped — GEMINI_API_KEY not set.")
        return None
    
    try:
        from google import genai
        client = genai.Client(api_key=GEMINI_API_KEY)
        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt
        )
        text = response.text
        if text:
            print(f"[LLM] [OK] Gemini ({GEMINI_MODEL}) responded successfully.")
            return {
                "status": "success",
                "model_used": f"{GEMINI_MODEL} (Gemini - Cloud)",
                "recommendation": text
            }
    except ImportError:
        print("[LLM] [ERROR] Gemini fallback failed — 'google-genai' package not installed. Run: pip install google-genai")
    except Exception as e:
        print(f"[LLM] [ERROR] Gemini fallback failed: {e}")
    return None

def generate_prompt(disease_name, confidence, dsi, severity, 
                   ideal_yield, final_yield, yield_loss_pct, 
                   soil_data, weather_data):
    """
    Constructs a structured prompt for the LLM based on the system's analytical outputs.
    """
    prompt = f"""You are an expert AI Agronomist assisting a maize farmer. 
Based on the following diagnostic and predictive data generated by our computer vision and machine learning models, provide a short, highly actionable, and professional recommendation report for the farmer.

=== DIAGNOSTIC REPORT ===
* Crop: Maize
* Disease Detected: {disease_name} (Confidence: {confidence*100:.1f}%)
* Disease Severity: {severity} (DSI: {dsi:.2f})

=== YIELD PREDICTION ===
* Ideal Yield (if 100% healthy): {ideal_yield:.2f} tons/hectare
* Projected Final Yield: {final_yield:.2f} tons/hectare
* Estimated Yield Loss due to disease: {yield_loss_pct:.1f}%

=== ENVIRONMENTAL CONDITIONS ===
* Soil Data: N={soil_data.get('N')} kg/ha, P={soil_data.get('P')} kg/ha, K={soil_data.get('K')} kg/ha, pH={soil_data.get('Soil_pH')}, Moisture={soil_data.get('Soil_Moisture')}%
* Weather: {weather_data.get('Rainfall')} mm rainfall, {weather_data.get('Temperature')}°C temp, {weather_data.get('Humidity')}% humidity, {weather_data.get('Sunlight_Hours')} hrs sunlight

Please structure your response with the following headers:
1. Disease Assessment: Briefly explain what exactly {disease_name} is and how dangerous it is.
2. Immediate Actions: Provide 2-3 precise chemical/biological treatments or interventions to stop the spread.
3. Yield Recovery Strategy: Can the {yield_loss_pct:.1f}% loss be mitigated? Suggest fertilizer/irrigation adjustments based on the soil (pH {soil_data.get('Soil_pH')}) and weather data provided.

Keep the tone professional, objective, and encouraging. Use bullet points for readability. Be concise.
"""
    return textwrap.dedent(prompt).strip()

def get_recommendations(disease_name, confidence, dsi, severity, 
                       ideal_yield, final_yield, yield_loss_pct, 
                       soil_data, weather_data,
                       model_name=DEFAULT_OLLAMA_MODEL):
    """
    Sends the prompt to an LLM and returns the generated insights.
    
    Fallback chain:
        1. Ollama (local) — free, private, no internet needed
        2. Gemini (cloud) — requires GEMINI_API_KEY env variable
        3. Error message — if both fail
    """
    prompt = generate_prompt(
        disease_name, confidence, dsi, severity, 
        ideal_yield, final_yield, yield_loss_pct, 
        soil_data, weather_data
    )
    
    # ── Try 1: Local Ollama ──
    result = _try_ollama(prompt, model_name)
    if result:
        return result
    
    # ── Try 2: Cloud Gemini ──
    result = _try_gemini(prompt)
    if result:
        return result
    
    # ── Both failed ──
    print("[LLM] [ERROR] All LLM providers failed.")
    return {
        "status": "error",
        "model_used": None,
        "recommendation": (
            "AI Recommendations Unavailable: Neither the local Ollama server nor "
            "the Gemini cloud API could be reached. To fix this:\n"
            "• Local: Run `ollama serve` in a terminal.\n"
            "• Cloud: Set the GEMINI_API_KEY environment variable."
        )
    }

# ==========================================
# Usage / Test execution
# ==========================================
if __name__ == "__main__":
    print("=" * 50)
    print("  Testing LLM Integration (Ollama → Gemini)")
    print("=" * 50)
    
    # Mock data simulating outputs from Models A, B, C, D
    mock_disease = "Common Rust"
    mock_conf = 0.9485
    mock_dsi = 0.67
    mock_severity = "Severe"
    
    mock_ideal_yield = 9.85
    mock_final_yield = 5.89
    mock_loss = 40.2
    
    mock_soil = {"N": 80, "P": 45, "K": 60, "Soil_pH": 6.5, "Soil_Moisture": 25.0}
    mock_weather = {"Rainfall": 900, "Temperature": 26, "Humidity": 60, "Sunlight_Hours": 8}
    
    print("\n[INFO] Trying Ollama first, then Gemini if needed...")
    
    result = get_recommendations(
        disease_name=mock_disease,
        confidence=mock_conf,
        dsi=mock_dsi,
        severity=mock_severity,
        ideal_yield=mock_ideal_yield,
        final_yield=mock_final_yield,
        yield_loss_pct=mock_loss,
        soil_data=mock_soil,
        weather_data=mock_weather,
    )
    
    print("\n" + "=" * 50)
    if result["status"] == "success":
        print(f"  AI RECOMMENDATIONS (Model: {result['model_used']})")
        print("=" * 50)
        print(result["recommendation"])
        with open("recommendation.txt", "w") as f:
            f.write(result["recommendation"])
    else:
        print("  LLM ERROR")
        print("=" * 50)
        print(result["recommendation"])

